name: Build and push

on:
  push:
    branches:
      - main

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish backend
        run: |
          pwd
          docker build . -t vishalkhanna995/ping-pong:$GITHUB_SHA
          docker push vishalkhanna995/ping-pong:$GITHUB_SHA

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image tag
        run: kustomize edit set image PING_PONG_IMG=vishalkhanna995/ping-pong:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kustomization.yaml'
          message: New version released ${{ github.sha }}